
export const popularProducts = [
    {
        id: 1,
        img: "https://i.ibb.co/FwynhHL/warrior-hockey-stick.webp",
        name: "Warrior Covert QR Edge Grip",
        sale_price: "$189.98",
        og_price: "$259.99",
        desc: "Covert QR Edge technology is unlike anything seen before in a hockey stick. We created the Edge Taper which maximizes the energy transfer by focusing the energy down into the blade for our fastest release yet.",
    },
    {
        id: 2,
        img: "https://i.ibb.co/64jzjzm/ccm-hockey-stick.webp",
        name: "CCM RibCor 76K Grip",
        sale_price: "$109.99",
        og_price: "$129.99",
        desc: "Featuring a low kick, traditional shaft design, ascent blade and a C6 Weave, CCM has continued to improve upon their already lightweight, quick-releasing RibCor stick. If you are looking for an entry level low kick stick, that will help your shots release as fast as possible, look no further than the CCM RibCor 76K Senior Hockey Stick!",
    },
    {
        id: 3,
        img: "https://i.ibb.co/bgqb30c/bauer-hockey-stick.webp",
        name: "Bauer Vapor 3X Grip",
        sale_price: "$159.99",
        og_price: "$189.99",
        desc: "The Vapor 3X Hockey Stick features an ultra-low kick point thanks to the addition of the XE Taper technology. This taper is narrower and oval shaped. This design helps stabilize the lower portion of the shaft, as well as the blade, during hard wrist shots, helping improve accuracy and control during shooting. This design also reduces the overall weight of the stick.",
    },
    {
        id: 4,
        img: "https://i.ibb.co/bQ4YpWg/sherwood-hockey-stick.webp",
        name: "Sherwood Rekker Element 1",
        sale_price: "$259.99",
        og_price: "$279.99",
        desc: "For the construction of the Rekker Element 1 Sherwood is using their Blackline XXV Carbon Fiber for the shaft and the blade. This lightweight carbon weave has over 25,000 filaments creating better stability and less torsional flex. The proprietary weaving of this material is known as Featherlite XT Technology.",
    },
    {
        id: 5,
        img: "https://i.ibb.co/vk06Cxb/bauer-hockey-skates.webp",
        name: "Bauer Vapor X3.7",
        sale_price: "$249.99",
        og_price: "$289.99",
        desc: "The Bauer X3.7 Hockey Skates features a digi comp quarter construction which will help develop a good stride and technique. This easier to flex boot will be more forgiving, allowing players to maintain and keep a good stride in any game situation.",
    },
    {
        id: 6,
        img: "https://i.ibb.co/Xy1SrrB/ccm-hockey-skates.webp",
        name: "CCM Ribcor 86K",
        sale_price: "$229.99",
        og_price: "$269.99",
        desc: "Brand new for 2021 are CCM's latest iteration of the Ribcor skate line, the CCM Ribcor 86K Ice Hockey Skates! This new skate is designed to help maximize agility on the ice and give a good balance of comfort fit and performance.",
    },
    {
        id: 7,
        img: "https://i.ibb.co/whcBVTF/graf-hockey-skates.webp",
        name: "Graf G755 Pro",
        sale_price: "$549.99",
        og_price: "$569.99",
        desc: "Features 2-piece heat moldable PE reinforced microfiber quarter panels with traditional stitched construction, Stiff tendon guard for max support, Tongue features 10mm protective felt to help prevent lace bite, Multi-density liner locks the heel into place for maximized energy transfer, Pre-molded internal liner with asymmetrical molded ankle pockets and heel pocket.",
    },
    {
        id: 8,
        img: "https://i.ibb.co/Qnkrg9F/true-hockey-skates.webp",
        name: "True TF7",
        sale_price: "$329.99",
        og_price: "$369.99",
        desc: "True is looking to transform the skate market once again, introducing its groundbreaking technology in the performance and competitive stock skate categories with the True TF7 Senior Ice Hockey Skates. Built around the fundamental player benefits that have become synonymous with true: best-in-class fit, best-in-class performance and versatile designs.",
    },
    {
        id: 9,
        img: "https://i.ibb.co/MV5mSVq/ccm-hockey-helmet.webp",
        name: "CCM Tacks 910 Hockey Helmet",
        sale_price: "$229.99",
        og_price: "$289.99",
        desc: "The interior of the Super Tacks 910 Helmet has been completely revamped when in comparison to its predecessor. Highlighting the protection aspect are the Fluid Inside pods plus D30 Smart Material, developed in collaboration with the Neurotrauma Impact Science Laboratory at the University of Ottawa. These pro-level protection pods are strategically placed within the inside of the helmet to dissipate the force of impacts. This includes direct impacts such as blocked shots to body checks!",
    },
    {
        id: 10,
        img: "https://i.ibb.co/cxw6GkC/warrior-hockey-gloves.webp",
        name: "Warrior Alpha DX3 Hockey Gloves",
        sale_price: "$129.99",
        og_price: "$149.99",
        desc: "For this iteration, Warrior has come up with the clever catchphrase known as Dynamic Strike. The thought process behind this was to give the Alpha DX3 Gloves the perfect balance of old-school traditional looks but have a new-school anatomical fit and feel! This close-to-the-hand feel provides improved puck control thanks to better grip of the stick, as well as advanced hand protection!",
    },
    {
        id: 11,
        img: "https://i.ibb.co/qN5Tx1f/warrior-hockey-shoulder.webp",
        name: "Warrior Alpha DX3 Shoulder Pads",
        sale_price: "$89.99",
        og_price: "$99.99",
        desc: "A vented internal jacket, known as the Dynamic ventilation, incorporated into the two-piece sternum pad keeps players cool, light, and mobile while out on the ice. Throughout the entirety of the pads, the Alpha DX3 Shoulder Pads feature a Strike Yellow Liner that helps wick away moisture, keeping players dry and comfortable during gameplay.",
    },
    {
        id: 12,
        img: "https://i.ibb.co/1sdXb7B/ccm-hockey-shin-guards.webp",
        name: "CCM Tacks 9060 Shin Guards",
        sale_price: "$99.99",
        og_price: "$109.99",
        desc: "Brand new for 2019 are the CCM Super Tacks 9060 Senior Shin Guards! As with the entirety of this new protective line from CCM Hockey, these shin guards were designed to give players elite protection, customizability, and comfort they seek to perform at their highest levels!",
    },
];